### ISSUE TITLE
Chybné request url při použití dodatečných parametrů

### ISSUE THREAD

**Issue by pmachan** [Kdyby/Facebook#21]
Když chceme použít dodatečnou selekci dat (třeba limit) v dotazu na Graph api nastává problém špatné request URL.

Pošleme do api:
```php
$facebook->api('{page-id}/posts?limit=5');
```
výsledné url je:
```text
https://graph.facebook.com/v2.1/{page-id}/posts?limit=5?access_token=......
```
Jak je vidět v url je zdvojený **?** pro parametry a neprojdeme přez OAuth

**An access token is required to request this resource. Code: 104**

Parametr limit se dá odeslat jako 3tí parameter API, ale je nutné psát metodu akce (v tomto případě GET)
```php
$facebook->api('{page-id}/posts', 'GET', [ 'limit' => 5 ]);
```
Při testování requestů v Graph API Exploreru vás to dost navádí psát parametry přímo do požadavku.

**Comment by Keeehi** [comment]
Nad tímto problémem jsem strávil taky několik hodin. Je pravda, že by se to mohlo chovat inteligentněji a poznat, že v té url už otazník je, ale aspoň že to funguje nějak.
já jsem se snažil o `/me?fields=id` a za odměnu jsem dostával
```
Kdyby\Facebook\FacebookApiException #2500
An active access token must be used to query information about the current user.
```
Tato exception mi tedy ani náhodou nenapověděla, o jaký problém se jedná.
To že mám využít třetí parametr jsem zjistil až když jsem si script odkrokoval. Sice to v dokumentaci je napsané, ovšem evidentně ne dost důrazně. Chtělo by tam někam výrazně připsat, že když bude v $pathOrParams string i včetně query části, tak že to nebude fungovat.

Předpokládám, že jak psal @pmachan o tom, že je pak nutné v druhém parametru mít GET tak úplně stačí, když tam mám null. Nebo se mýlím?

**Comment by fprochazka** [comment]
Díky za report, už by měly fungovat obě varianty.
