### ISSUE TITLE
Ověření požadovaných práv

### ISSUE THREAD

**Issue by pitrrs** [Kdyby/Facebook#26]
Ahoj,

je nějaká možnost znovu ověřit přidělená práva (požadovaná na základě configu)?

Díky

**Comment by fprochazka** [comment]
Jasně, stačí přesměrovat zase na pomocí login komponenty na facebook. 

https://developers.facebook.com/docs/facebook-login/permissions/v2.2?locale=cs_CZ

**Comment by fprochazka** [comment]
Ref #27
