### ISSUE TITLE
Deprecated facebook-php-sdk

### ISSUE THREAD

**Issue by integer** [Kdyby/Facebook#28]
Původní fb knihovna byla nedávno označena jako deprecated ( https://github.com/facebookarchive/facebook-php-sdk/commit/8e7e7951e99d86b68ce1135537d559663d759af0 ) a nově se má požívat jiná verze sdk.

Bude na to kdyby/facebook nějak reagovat? Rozhoduju se na čem založit přepis současné app, která využívá staré api. Díky

**Comment by fprochazka** [comment]
Ta nová SDK od facebooku je naprosto nechutná sračka která vůbec nedává smysl. Kdyby už dávno podporuje api v2.1, stačí ho povolit :)  https://github.com/Kdyby/Facebook/commit/c7dcdcf675fc2e9cd717423e40998d21390e5d4f
