### ISSUE TITLE
Double monitor on presenter overwrites parameters

### ISSUE THREAD

**Issue by jiripudil** [Kdyby/Facebook#33]
We're trying to issue a rerequest on Facebook API via `{link fbLogin-open! fbLogin-authType => 'rerequest'}` (the parameter was introduced in #30). The problem is that Kdyby/Facebook's `AbstractDialog` [adds its own monitor on `IPresenter`](https://github.com/Kdyby/Facebook/blob/e1263da7414b55d9882db95c03f5ee6d88c8042d/src/Kdyby/Facebook/Dialog/AbstractDialog.php#L72), while Nette by default [adds a monitor on `UI\Presenter`](http://api.nette.org/2.3.0/source-Application.UI.PresenterComponent.php.html#73).

Therefore the [`attached`](http://api.nette.org/2.3.0/source-Application.UI.PresenterComponent.php.html#53-64) method gets called twice: In the first run, it *pops* the passed `authType` parameter from presenter's global space and passes it to the component, but in the second run it replaces the parameter with now empty array.

Does the monitor on `IPresenter` have some special purpose or can it be removed? Or is there some other way out of this?

(cc @VBoss)

**Comment by fprochazka** [comment]
Ref #32
