### ISSUE TITLE
$fb->getUser vracia vždy nulu. 

### ISSUE THREAD

**Issue by PeterBocan** [Kdyby/Facebook#35]
Ahoj, mám urgentný prípad, nainštaloval som Kdyby pomocou Composera, riadil sa dokumentáciou - nastavil config, použil kód z dokumentácie. 

Facebook vracia OAuthException 2500 - blbý access token. Používam Facebook API v2.3 a staviame webovú a canvasovú aplikáciu. Nejaká nápoveda, čo sa mohlo posrať?

*edit*: Doplním, že aplikácia mi naozaj pribudne na Facebooku a naozaj som jej pridelil práva. Teda Facebookom to prejde.  

Ďakujem za odpoveď.
Peter Bočan.

**Comment by TomasA** [comment]
Mám obdobný problém,
postupoval jsem podle návodu.

Facebook mi vrací kód 200, ale getUser() mi vždy vrací 0.

Používám API v2.3, vytvářím webovou aplikaci.

Děkuji za radu,
T.A.

**Comment by PeterBocan** [comment]
Používal som verziu "v2.3" zrejme je tam niekde vnútorný problém. Dropol som to na "v2.1" a ide mi to.

**Comment by fprochazka** [comment]
Nechcete to někdo debugnout? My jedeme na `graphVersion: v2.2` a funguje to dobře.

**Comment by PeterBocan** [comment]
a teraz som sa vrátil k verzii 2.3 a ono to zázračne ide. Zrejme bude problém s predávaním získaného access tokenu (alebo invalidácia cache apod.), pretože predtým mi predávalo naspäť do Facebooku application access token - fallback v getUserAccessToken.

**Comment by fprochazka** [comment]
Login s v2.3 fixed in master https://github.com/Kdyby/Facebook/commit/f20e57f07c60b0740912c19353a1ef9901ccf60b

**Comment by fprochazka** [comment]
Díky za report!
