### ISSUE TITLE
Undefined index: appsecret_proof

### ISSUE THREAD

**Issue by MartinMystikJonas** [Kdyby/Facebook#36]
Not sure what changed. We start getting this notice after upgrade:

    PHP Notice: Undefined index: appsecret_proof in /var/www/flowlist/libs/kdyby/facebook/src/Kdyby/Facebook/Api/CurlClient.php:217

Problem occures in code from my PR #22. But I'm not sure why this error show now.

So the question is: should I fix my code (add isset check) or is this unintentional side effect of some other change and should be fixed elsewhere?

**Comment by fprochazka** [comment]
Yeah, the conditions should be a bit smarter.

**Comment by MartinMystikJonas** [comment]
Fix in PR #37
