### ISSUE TITLE
Errors in tracy panels

### ISSUE THREAD

**Issue by Lexinek** [Kdyby/Facebook#47]
During the login process all panels seem to not work, please see screenshot to better understand the problem.

![screenshot](https://photos-4.dropbox.com/t/2/AAC4S9A5vAZOkspRPbpfd4jmPUrxoHZAB5Nuupg2wnVJfA/12/120809986/png/32x32/3/1471730400/0/2/Screenshot%202016-06-23%2013.12.30.png/EPrQkV0YgusIIAcoBw/BQ7aLFWJKsw1aQ1U5zpZwWaYhYTYDdav43kaXejzdyI?size_mode=3&dl=0&size=2048x1536)

Though everything seem to work as intended except those error messages.

**Comment by fprochazka** [comment]
The screenshot is broken, next time please upload it using the github interface, it will survive longer. Closing as wont fix.
