### ISSUE TITLE
Nette 2.3.7 and tracy panel bug?

### ISSUE THREAD

**Issue by matak** [Kdyby/Facebook#50]
see the error in attachment

<img width="1246" alt="snimek obrazovky 2016-08-29 v 22 20 02" src="https://cloud.githubusercontent.com/assets/164995/18066375/81637d14-6e38-11e6-9f9d-3e5f68f50f14.png">

**Comment by matej21** [comment]
It should work with nette/utils 2.3.10

**Comment by Mart78** [comment]
In Nette 2.4 there is another error
![fb-tracy](https://cloud.githubusercontent.com/assets/7780566/18265677/37ac83ca-7417-11e6-8ed0-df4fe390a043.PNG)

**Comment by fprochazka** [comment]
Imho fixed with a0752c4
