### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by simPod** [Kdyby/Facebook#57]
Asking whether I should wait for PRs to be merged or manage my own fork. Thanks!

**Comment by fprochazka** [comment]
@simPod are you interested in maintaining this repository?

**Comment by simPod** [comment]
@fprochazka I prefer to PR but wasn't sure whether they would be ever merged. However, if necessary, I can help maintaining. Better to maintain this than my own

**Comment by enumag** [comment]
At this point this repo can be considered as dead. I can merge some bugfixes but I probably won't merge features since I never even used this library. If you're still interrested in maintaining this I'll gladly give you the access.

**Comment by simPod** [comment]
Nah, thanks. It would not be wise to rely on unmaintained kdyby libraries so I don't use them anymore. I prefer to dedicate my time to active and perspective OSS projects. Thanks for comment though.

**Comment by enumag** [comment]
@simPod Understood, this is indeed the better approach. Good luck.

**Comment by simPod** [comment]
Maybe if you have access, consider marking this repo as abandoned so newcomers are not unpleasantly surprised after integrating this into their project 🤔 Not sure if you have access to packagist as well.

**Comment by enumag** [comment]
I have access to all Kdyby packages. I'll do as you said.

**Comment by fprochazka** [comment]
FYI, I suggest using https://github.com/thephpleague/oauth2-facebook

**Comment by fprochazka** [comment]
@simPod otherwise, if you want to really use this repo, I'd be happy to give you the rights to maintain it.

**Comment by enumag** [comment]
Oh looks like I was wrong. I don't have access to packagist for Kdyby. Can you grant me the access @fprochazka?

**Comment by fprochazka** [comment]
![image](https://user-images.githubusercontent.com/158625/38705561-378b441c-3eaa-11e8-9175-c41c2b3d3bb9.png)

**Comment by fprochazka** [comment]
@enumag next time please consult me before "abandoning" any more repos :) In this case it's a simple decision, but there is still a lot of projects depending on some packages and there is still a chance people might be willing to take over and start taking care of the lib.

**Comment by enumag** [comment]
@fprochazka Roger. For now I'd like to mark as abandoned Google, GitHub, GeocoderSeznamMaps and DoctrineDbalBatchImport. I'm definitely not going to mark as abandoned things like Events, Autowired etc, any time soon, you don't need to worry about that.

**Comment by fprochazka** [comment]
`Google`, `GitHub`, `DoctrineDbalBatchImport` ... but is there a reason to abandon `GeocoderSeznamMaps`? Worked fine list time I checked.

**Comment by enumag** [comment]
You're right. GeocoderSeznamMaps doesn't seem to use anything that would not work on PHP 7.2 so it's fine.
